import { Link } from "react-router-dom";
import { GitBranch, ArrowLeft } from "lucide-react";

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    body: `By accessing or using the Rootline platform ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, you may not access or use the Service. We reserve the right to update these Terms at any time; continued use of the Service after any modification constitutes your acceptance of the revised Terms.`,
  },
  {
    title: "2. Description of Service",
    body: `Rootline is a genealogical documentation platform that enables authenticated users to record family members, define relationships, generate interactive family tree visualisations, and share tree access with other registered users. The Service is provided on an "as-is" and "as-available" basis.`,
  },
  {
    title: "3. Account Registration",
    body: `You must create an account to use the Service. You agree to provide accurate, current, and complete information during registration and to update such information as necessary to keep it accurate. You are solely responsible for maintaining the confidentiality of your credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorised use of your account.`,
  },
  {
    title: "4. Data Ownership and Intellectual Property",
    body: `You retain full ownership of all genealogical records, biographical data, photographs, and annotations you submit to the Service ("User Content"). By submitting User Content, you grant Rootline a limited, non-exclusive licence to store, process, and display your User Content solely for the purpose of providing the Service to you and to any users to whom you explicitly grant access. Rootline claims no intellectual property rights over your User Content.`,
  },
  {
    title: "5. Responsible Use and Consent",
    body: `You represent and warrant that you have obtained any necessary consents required by applicable data protection law before recording the personal information of living third parties on the platform. You agree not to use the Service for any unlawful purpose, including but not limited to the unauthorised collection, processing, or distribution of personal data.`,
  },
  {
    title: "6. Sharing and Access Control",
    body: `The Service allows you ("Owner") to grant other registered users access to your family tree with defined permission levels: Owner, Editor, or Viewer. You acknowledge that persons you invite with Editor access may modify records within your tree. Rootline does not independently verify the identity of invited users; you assume responsibility for all sharing decisions. Trees belonging to different users remain strictly isolated and are never automatically merged.`,
  },
  {
    title: "7. Prohibited Conduct",
    body: `You agree not to: (a) use the Service to transmit unsolicited communications; (b) attempt to gain unauthorised access to other users' accounts or data; (c) reverse-engineer, decompile, or disassemble any portion of the Service; (d) use automated tools to scrape, index, or extract data; (e) impersonate any person or entity; or (f) use the Service in any manner that could damage, disable, overburden, or impair our infrastructure.`,
  },
  {
    title: "8. Disclaimer of Warranties",
    body: `The Service is provided without warranties of any kind, whether express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, and non-infringement. Records generated by the Service are an organisational aid and do not constitute formal legal proof of identity, family relationship, property ownership, or estate inheritance. You should consult qualified legal and genealogical professionals for any legally consequential matters.`,
  },
  {
    title: "9. Limitation of Liability",
    body: `To the maximum extent permitted by applicable law, Rootline and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of data, loss of profits, or business interruption, arising out of or in connection with your use of the Service, even if advised of the possibility of such damages.`,
  },
  {
    title: "10. Termination",
    body: `We reserve the right to suspend or terminate your account and access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is otherwise harmful to the Service, other users, or third parties. Upon termination, your right to use the Service ceases immediately.`,
  },
  {
    title: "11. Governing Law",
    body: `These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the competent courts of the applicable jurisdiction.`,
  },
  {
    title: "12. Contact",
    body: `If you have questions about these Terms, please contact us at: support@rootline.app`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen w-full bg-[#F7F5F0] flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-40 grid grid-cols-[1fr_auto_1fr] items-center px-8 lg:px-16 py-5 border-b border-[#E7E2D6] bg-[#F7F5F0]/95 backdrop-blur-sm">
        <Link
          to="/"
          className="flex items-center gap-1.5 w-fit hover:opacity-85 transition-opacity"
          aria-label="Rootline Home"
        >
          <GitBranch className="w-4 h-4 text-[#1C4B3C]" strokeWidth={2.5} />
          <span className="text-[13px] tracking-[0.2em] font-semibold text-[#1C4B3C]">ROOTLINE</span>
        </Link>
        <div />
        <div className="flex justify-self-end">
          <Link
            to="/"
            className="flex items-center gap-1.5 text-sm font-medium text-[#6B7280] hover:text-[#1C1F1D] transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="flex-1 px-8 lg:px-16 py-16 max-w-3xl mx-auto w-full">
        {/* Page header */}
        <div className="mb-12">
          <p className="text-[11px] tracking-[0.2em] font-semibold text-[#C9A468] mb-3 uppercase">Legal</p>
          <h1 className="text-3xl lg:text-4xl font-serif font-bold text-[#1C1F1D] mb-4">
            Terms of Service
          </h1>
          <p className="text-sm text-[#9CA3AF]">
            Effective date: 1 September 2025 · Last updated: 18 September 2025
          </p>
        </div>

        {/* Intro */}
        <div className="bg-white border border-[#E7E2D6] rounded-2xl px-7 py-6 mb-10 text-sm text-[#4B5563] leading-relaxed">
          <p>
            Please read these Terms of Service carefully before using the Rootline platform. These Terms form a legally binding agreement between you and Rootline governing your access to and use of the Service.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {SECTIONS.map(({ title, body }) => (
            <section key={title}>
              <h2 className="text-base font-semibold text-[#1C1F1D] mb-2">{title}</h2>
              <p className="text-sm text-[#4B5563] leading-relaxed">{body}</p>
            </section>
          ))}
        </div>

        {/* Footer note */}
        <div className="mt-14 pt-7 border-t border-[#E7E2D6]">
          <p className="text-xs text-[#9CA3AF] leading-relaxed">
            These Terms of Service were last updated on 18 September 2025. By continuing to use Rootline after this date, you acknowledge that you have read, understood, and agree to be bound by the current Terms.
          </p>
          <div className="flex items-center gap-6 mt-5">
            <Link to="/privacy" className="text-xs font-medium text-[#1C4B3C] hover:underline">
              Privacy Policy →
            </Link>
            <Link to="/" className="text-xs text-[#6B7280] hover:text-[#1C1F1D] transition-colors">
              Return to home
            </Link>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="px-8 lg:px-16 py-8 border-t border-[#E7E2D6]">
        <div className="max-w-3xl mx-auto flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between">
          <p className="text-xs text-[#9CA3AF]">© {new Date().getFullYear()} Rootline. All rights reserved.</p>
          <div className="flex items-center gap-5 text-xs text-[#6B7280]">
            <Link to="/terms" className="hover:text-[#1C1F1D] transition-colors font-medium text-[#1C1F1D]">Terms</Link>
            <Link to="/privacy" className="hover:text-[#1C1F1D] transition-colors">Privacy</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
